/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120493-g9a32b86307-20250804"
#endif /* AVUTIL_FFVERSION_H */
